service: Remindmethis
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

  environment:
    CONSUMER_KEY: "PfF6Ey2Vx862ceyz15DMqARaW"
    CONSUMER_SECRET: "Tio3LJPlq1sH8DT7LVVVA3jY4yeaGh9X2v7chDxDR8SnqyopQX"
    BEARER_TOKEN: "AAAAAAAAAAAAAAAAAAAAAOBNkAEAAAAApF4Uvcshs93%2FOkzhZvwDNVXGSts%3DPngucLkFOMDL3nTkaaq8vfsP5cGxHwOk4pwOsMKFgjLniGryri"
    ACCESS_TOKEN: "1561081114306813952-jcBKM3pAvLyF3uZkOPrnahn6skyoR0"
    ACCESS_TOKEN_SECRET: "mntUrFe8laTHt2SwkWZa4FWgi8ntDGaag3q5FYvXDV02m"
    CLIENT_ID: "c0x2RXlrYnZsRlJQQ09tODhwZEk6MTpjaQ"
    CLIENT_SECRET: "Yja3f53JngKP-sUirjHF0mgdrdD-Bra8WgZH4G0RimbCjB8LLj"
    MONGODB_URL: "mongodb+srv://cshewale23:Chinmay123@cluster0.yziusso.mongodb.net/app"
    USER_ID: "1606266324094955521"
    CALLBACK_URL: "http://127.0.0.1:3000/callback"
    BASE_URL: "http://127.0.0.1:3000/"


functions:
  webhook:
    handler: handler.webhook
    timeout: 30
    events:
      - httpApi: "*"

  checkReminder:
    handler: handler.checkReminder
    timeout: 20
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-offline
